### ISSUE TITLE
Not my public IP in the invoice's node info

### ISSUE THREAD

**Issue by BobleChinois** [btcpayserver/woocommerce-plugin#11]
I run BTCPay on a small home server. I paired it with a Woocommerce, created a test product and got an invoice for a lightning payment.

On the node info, I read this : 
`02d0776e38d9f02bb435f6b2743a95aa961d4a3df6a4e854f5fb8454f32372368c@127.0.0.1:9735`

Isn't the IP address supposed to be my public IP, so that other nodes can connect with me ? 

Clightning `getinfo` returns my public IP under `address`.

**Comment by NicolasDorier** [comment]
Are you using docker?

**Comment by NicolasDorier** [comment]
Can you send me the output of your `getinfo`?

**Comment by BobleChinois** [comment]
Yes I'm using Docker, 
This is very strange, I turned off BTCPay yesterday and turn it on again, but the address returned by `getinfo` is different, I'm sure it was my public IP yesterday.
This is the output now : 
```
{
  "id": "02d0776e38d9f02bb435f6b2743a95aa961d4a3df6a4e854f5fb8454f32372368c", 
  "port": 9735, 
  "address": [
    {
      "type": "ipv4", 
      "address": "127.0.0.1", 
      "port": 9730
    }
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "basedon-aeafe4dbe7d5c61f664c18417698866b0d70252f-modded", 
  "blockheight": 1411945, 
  "network": "testnet"
}
```
I also created an invoice, and the node info is still `02d0776e38d9f02bb435f6b2743a95aa961d4a3df6a4e854f5fb8454f32372368c@127.0.0.1:9735`

**Comment by NicolasDorier** [comment]
It is normally taking your `BTCPAY_HOST`, have you properly configured it to not be `localhost` but your custom domain?

**Comment by BobleChinois** [comment]
This is the output of my `.env` file : 
```
BTCPAY_HOST=sosthenebtcpay.pw
ACME_CA_URI=https://acme-v01.api.letsencrypt.org/directory
NBITCOIN_NETWORK=testnet
LETSENCRYPT_EMAIL=
LIGHTNING_ALIAS=
```

**Comment by NicolasDorier** [comment]
this is super strange, never had such bug. I don't manage to connect to `sosthenebtcpay.pw`. (connection timeout)

You are using clightning?

Can you send the output of `docker inspect btcpayserver_clightning_bitcoin`?

Probably unrelated, but testnet3 is having lot's of block and reorg this day, it might cause btcpay to freeze.

**Comment by NicolasDorier** [comment]
Ah I maybe know, are you redirecting `sosthenebtcpay.pw` to `127.0.0.1` in your hosts by any chance? In this case, your docker will resolve 127.0.0.1 instead of the right external ip.

**Comment by BobleChinois** [comment]
It is normal that you couldn't connect to `sosthenebtcpay.pw` yesterday, as I turned off BTCPay to investigate on another more general issue impacting my computer (I thought that it might be related to BTCPay, turned out that the issue showed up again anyway).

Yes, I'm using c-lightning.

Turned out that I indeed registered `sosthenebtcpay.pw` as localhost in my `hosts` file. What was I thinking ? 

I'll see first if it solved my problem and closed the issue if everything is ok. Thanks !

**Comment by NicolasDorier** [comment]
@BobleChinois you were probably testing before having the certificate.

**Comment by BobleChinois** [comment]
Now the output of `getinfo` and the `node info` of the invoice are both correct. Problem solved, thanks

**Comment by BobleChinois** [comment]
Mmmhhh maybe I talked a bit too fast, the IP is correct, but I just realized that the port is 9735.
I changed external port in the `docker-compose.generated.yml` file as such : 
```
  clightning_bitcoin:
    image: nicolasdorier/clightning:v0.6
    container_name: btcpayserver_clightning_bitcoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/bitcoin
        bitcoin-rpcconnect=bitcoind
        announce-addr=${BTCPAY_HOST}:9730
        bind-addr=0.0.0.0:9735
        network=${NBITCOIN_NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
        chain=btc
    volumes:
    - "clightning_bitcoin_datadir:/root/.lightning"
    - "bitcoin_datadir:/etc/bitcoin"
    ports:
    - "9730:9735"
    links:
    - bitcoind
```
The `getinfo` output : 
```
{
  "id": "02d0776e38d9f02bb435f6b2743a95aa961d4a3df6a4e854f5fb8454f32372368c", 
  "port": 9735, 
  "address": [
    {
      "type": "ipv4", 
      "address": "5.51.82.169", 
      "port": 9730
    }
  ], 
  "binding": [
    {
      "type": "ipv4", 
      "address": "0.0.0.0", 
      "port": 9735
    }
  ], 
  "version": "basedon-aeafe4dbe7d5c61f664c18417698866b0d70252f-modded", 
  "blockheight": 1412259, 
  "network": "testnet"
}
```

**Comment by NicolasDorier** [comment]
Since last version I am taking `address/port`, because `port` is removed in the next version. Can you just update btcpay?

**Comment by BobleChinois** [comment]
I did a `btcpay-update`, and it seems to have solved the issue. Thanks :pray:
