### ISSUE TITLE
Bitcore BTX support

### ISSUE THREAD

**Issue by dalijolijo** [btcpayserver/woocommerce-plugin#16]
The integration of Bitcore BTX in btcpayserver is completed. What is needed to integrate Bitcore BTX for woocommerce-plugin?

**Comment by Kukks** [comment]
Nothing, as long as btx is enabled on the store it is paired to, you are
good to go.

**Comment by dalijolijo** [comment]
How can I run the woocommerce-plugin with the docker solution btcpayserver-docker? Where can I find complete instructions?
I only found the docker build/run instructions here: https://github.com/btcpayserver/woocommerce-plugin#build-with-docker
Or there a way (and documentation) to integrate the woocommerce-plugin-docker inside the docker-compose of btcpayserver-docker?

**Comment by Kukks** [comment]
You do not integrate with docker. You must run an
independent wordpress site and follow the guide at
https://docs.btcpayserver.org/integrations/woocommerce
ᐧ

**Comment by bitcoinshirt** [comment]
@dalijolijo it looks like your question has been answered, if so, please close the issue.
