### ISSUE TITLE
Checkout popup without leaving the site pag

### ISSUE THREAD

**Issue by darkban** [btcpayserver/woocommerce-plugin#18]
guys how can I checkout via popup without leaving the site page? who helps me?

**Comment by bitcoinshirt** [comment]
You keep asking this on Slack even though you got a reply.
That feature is called modal, and it's not implemented yet. Please stop asking same question via multiple channels.

**Comment by darkban** [comment]
Se faccio la stessa domanda in più canali è solo perché non c'è nessuno che mi degna di una risposta come te. È solo la modifica di una riga di comando e un aggiunta di un caricamento js ma non capisco come implementarlo... speravo che qualcuno mi aiutasse nell'implementazione perché qui potesse essere utile a me e ad altei come me tutto qui.
If I ask the same question in more than one channel, it's just because there's no one who deserves a response like you. It's just editing a command line and adding an upload js but I do not understand how to implement it ... I was hoping someone would help me with the implementation because here it would be useful for me and for the highs like me here.

**Comment by bitcoinshirt** [comment]
If you keep asking same question, you're diverting the time developers can spend actually working on it. The feature is not implemented. And also, you already got a reply. So stop asking same question over and over again, it does not benefit anyone.

I replied to many of your question, so you're just being rude now.

**Comment by darkban** [comment]
If I gave the impression of being rude I apologize but it was not my intention I just wanted to know everything here. sorry :(

**Comment by bitcoinshirt** [comment]
I understand that you want a certain feature, but there are lots of features that should be added prior to this.

As I mentioned already, if certain feature is critical for your business, fund a developer that can implement it for you, if it's not urgent, wait, it will be added at some point, but there's no ETA.
