### ISSUE TITLE
Issue with order statuses

### ISSUE THREAD

**Issue by ihqtzup** [btcpayserver/woocommerce-plugin#29]
"BTCPay invoice confirmed. Awaiting payment completed status."
After that, the order has been processed and marked as complete.

"BTCPay invoice payment completed. Payment credited to your merchant account."

The order goes from Complete to Processing status again. This is a serious issue. It should be checked if the status is already complete and if so, do not change it to back to a processing status.

**Comment by NicolasDorier** [comment]
@ihqtzup can you share your BTCPay plugin mapping?

**Comment by ihqtzup** [comment]
<img width="490" alt="Näyttökuva 2019-7-18 kello 17 07 00" src="https://user-images.githubusercontent.com/1743396/61464564-28aedd00-a97f-11e9-9c1d-6f72a14709c3.png">

**Comment by NicolasDorier** [comment]
@ihqtzup as you can read, your settings specifically says: If the invoice is confirmed or completed, set the status to processing.

**Comment by ihqtzup** [comment]
No, it does not solve the problem as you might first think of it. All orders should be in the processing-status until they are processed and shipped. If I put in the settings Complete: Complete instead of Complete: Processing, then the order goes to complete status immediately after the BTCPay invoice is complete. So, for example, all orders made during the weekend would be marked as complete, and they will never get processed and shipped actually.

**Comment by ihqtzup** [comment]
"they will never get processed and shipped actually." well this is just for example that you understand what I mean. We have procedures and checks that this can not actually happen, but this is still an issue. **You should definitely always check the current order status before updating it.** It does not make sense to update complete order to processing automatically. That would be very easy to fix in the code.

**Comment by NicolasDorier** [comment]
So if I understand your:

1. Order come
2. Customer pays => On Hold
3. Confirmed => Order go to processing
4. You manually put the order to "complete" 
5. Completed => Order go back to processing

You are telling me that completed should not put back to processing?

If that's the case, just put the "Complete" state to "blank" so that woocommerce ignore it.

**Comment by ihqtzup** [comment]
Ahh, I see. I will try that out! Thank you very much!

**Comment by NicolasDorier** [comment]
please close this issue if it solves your issue.
