### ISSUE TITLE
Access Denied When Trying To Get A Pairing Code

### ISSUE THREAD

**Issue by gianisss** [btcpayserver/woocommerce-plugin#34]
Whenever I try to get a pairing code for my store the https://btcpay.host/api-tokens, it redirects me to basically a blank page (only the Header with menu plus footer are visible the rest in between where the pairing should happen is blank).

The only feedback I can get is the structure of the URL:

https://btcpay.host/Account/AccessDenied?ReturnUrl=%2Fapi-tokens

Can't quite figure out what's wrong. The SSL is set up properly - no browser notifications, using https://www.ssllabs.com/ssltest my BTCPay server is ranked A+ my WP site is ranked A

**Comment by pavlenex** [comment]
Replicated, this is indeed a bug. Thanks for reporting.

Pinging @Kukks @NicolasDorier

**Comment by pavlenex** [comment]
@gianisss what you can do is pair manually. This is a workaround.

In your BTCPay, go Stores > Settings > Access Tokens > Create access token. Leave it empty, though you can add label name.  Click `Request Pairing`. Then Approve. Copy the  Server initiated pairing code in your WooCommerce. And save changes in Woo.

**Comment by gianisss** [comment]
Worked with the manual pairing as described by @pavlenex Thank you! Will keep it open since you confirmed it is a bug and leave it up to the devs to close it

**Comment by pavlenex** [comment]
Glad to hear that, yup, let's leave it opened since it's a bug that has to be addressed.

**Comment by NicolasDorier** [comment]
I am on it, probably caused by me during permission refactoring.

**Comment by NicolasDorier** [comment]
Closing this, will release a new version of btcpay today with this bug fix (1.0.3.136)
