### ISSUE TITLE
POST /wc-api/WC_Gateway_BtcPay/ 500

### ISSUE THREAD

**Issue by gillesgoetsch** [btcpayserver/woocommerce-plugin#35]
For the record, cause I didn't found the solution online.

I've setup a btcpayjungle server and using this plugin.

When an order is pending, my access log shows:
`XX.XXX.XXX.XXX - - [04/Nov/2019:20:32:29 +0100] "POST /wc-api/WC_Gateway_BtcPay/ HTTP/1.1" 500 6538 "-" "-"`

Server Events showing:
`Error while sending IPN (1003 invoice_paidInFull): Unexpected return code: 500`

WooCommerce-BTCPay Error Log shows:
`The BTCPay payment plugin was called to process an IPN message but could not retrieve the order details for order_id: "59287". If you use an alternative order numbering system, please see class-wc-gateway-btcpay.php to apply a search filter.`

I'm using the "WooCommerce Sequential Order Numbers" Plugin.
Order expires in WC-Admin after several 500, even though it was paid.

**Comment by gillesgoetsch** [comment]
It's happening because you use a different order number system.

See class-wc-gateway-btcpay.php telling you:

```
	    //this is for the basic and advanced woocommerce order numbering plugins
	    //if we need to apply other filters, just add them in place of the this one
            $order_id = apply_filters('woocommerce_order_id_from_number', $order_id);

            $order = wc_get_order($order_id);
```

This solves the issue and returns the correct order_id:

```/**
 * Get correct order id for BTCPay Order
*/

function _theme_get_sequential_order_id($order_id) {
    $seq_id = wc_sequential_order_numbers()->find_order_by_order_number( $order_id );

    if($seq_id) {
        return $seq_id;
    } else {
        return $order_id;
    }
}
add_filter( 'woocommerce_order_id_from_number', '_theme_get_sequential_order_id' );
```

**Comment by Kukks** [comment]
https://docs.btcpayserver.org/faq-and-common-issues/faq-integrations#error-if-you-use-an-alternative-order-numbering-system-please-see-class-wc-gateway-btcpay-php-to-apply-a-search-filter
