### ISSUE TITLE
Can not connect Woocommerce to BTCPay Server - Tor

### ISSUE THREAD

**Issue by PsychedelicHell** [btcpayserver/woocommerce-plugin#36]
I am unable to run BTCPay Server via the standard HTTPS way and instead I am trying to use TOR.

When linking the Woocommerce plug-in with BTCPay Server I receive an error "cannot resolve host" with a link to my Tor server (which works when you click on it)

![Can't pair to Woocommerce](https://user-images.githubusercontent.com/57477439/68478834-f9511280-0284-11ea-9062-11a2b1d2f9b7.png)

This is the last step I need to take to get BTC working on my online shop, I have no idea what I can do to fix this, please help.

**Comment by NicolasDorier** [comment]
@PsychedelicHell using onion website on your woocommerce, even if it would work, would be unusable for your customer because it would require them to use Tor browser.

If that's OK for you though, you should take a look at google searching for "route all traffic through tor". Myself, I don't really know how to do this.

**Comment by PsychedelicHell** [comment]
Hey Nicolas, to clarify my WordPress site is normal HTTPS. I was just running BTCpPy with Tor. 

> Why? Requirement or you did not managed to?
Because I already have my Bitnami WordPress installed as a stand alone virtual machine running on port 80 and 443. 

I know I can run BTCPay server with the WooCommerce additional fragment but I found it crashed alot and would prefer to keep my word press on a seperate VM to my BTCPay server. 

It's there any other way I can get it to work? Nothing I can do to get the plug in working across https with the Tor server? Or is my only choice to run the woo commerce add on within BTCPay docker?

**Comment by NicolasDorier** [comment]
> I was just running BTCPay with Tor.

The woocommerce website will redirect the customer to btcpay so you don't want BTCPay to be on Tor if your woocommerce is on https.

> It's there any other way I can get it to work? Nothing I can do to get the plug in working across https with the Tor server? Or is my only choice to run the woo commerce add on within BTCPay docker?

Just make HTTPS work with your btcpay server, what's the matter?

**Comment by PsychedelicHell** [comment]
> Just make HTTPS work with your btcpay server, what's the matter?
I don't like hosting my Woocommerce site within BTCPayServer. I want to run them on separate VM's.

My problem with that is SSL encryption and port forwarding issues. I don't understand how to self-host a Woocommerce website & BTCPayServer on separate VM's whilst still having SSL on both of them (due to them both needing ports 80 and 443).

**Comment by NicolasDorier** [comment]
Tor is not the answer for your problem.

There is no simple solution to solve this, you need HTTPS for your BTCPay, not Tor, because your customer don't have Tor.

> .I know I can run BTCPay server with the WooCommerce additional fragment but I found it crashed alot and would prefer to keep my word press on a seperate VM to my BTCPay server.

Your best bet is to fix this problem. Did you found out why it was crashing? What is happening when it is "crashing"?

**Comment by PsychedelicHell** [comment]
Hey Nicolas,

No worries mate, I will stop trying with the impossible.

![image](https://user-images.githubusercontent.com/57477439/68527175-37f3d500-0338-11ea-9bdb-4afc2317e271.png)

How can I get SSL encryption on these ports 8080 and 8443 working?

**Comment by NicolasDorier** [comment]
@PsychedelicHell you probably can by having an additional reverse proxy on top of btcpay server one, but frankly I don't know how to do and I would not do it if I were you. The best is to try to make Woocommerce work with the opt-add-woocommerce on the btcpayserver VM.

**Comment by pavlenex** [comment]
@PsychedelicHell not sure if you figured this one out, but you can very easily deploy Woo on top of your existing btcpay via a simple env variable we have.

Check [documentation ](https://docs.btcpayserver.org/integrations/woocommerce#deploying-woocommerce-from-btcpay-server)and also this [article ](https://medium.com/@BtcpayServer/btcpay-woocommerce-cheap-ab6fcdd97075)that explains it.

**Comment by PsychedelicHell** [comment]
I managed to get it working with an Nginx reverse proxy, redirecting port 80/443 requests to my individual virtual machines and now BTCPay  Server is working with my WordPress sites.
