### ISSUE TITLE
Status not changing

### ISSUE THREAD

**Issue by ThoKolKol** [btcpayserver/woocommerce-plugin#40]
No matter if the order is paid, fully confirmed or invoice expired, status remains "Pending".

WooCommerce: Version 3.9.0
BTCPay for WooCommerce: Version 3.0.10

I tried 4 third-party hosts. In wordpress error log is literally nothing from BTCPayserver plugin. 

<img width="424" alt="Zrzut ekranu 2020-01-27 o 09 52 04" src="https://user-images.githubusercontent.com/60340024/73160983-b3208800-40ea-11ea-9534-33ca433db5bd.png">

`01-27-2020 @ 04:12:18 - BTCPay Woocommerce payment plugin object constructor called. Plugin is v3.0.10 and server is PHP v7.0
01-27-2020 @ 04:12:18 -     [Info] $this->api_key            = SGpQWTBoSExIYnJPT2NEM2ZvNUdYb0t6WldVUUNyOVAwVGgyTU9wNk5ET3JxeFhQQW1xRm5Zb3pZTGJjbUw2NWd5ZXZzRjdRR2E1Sm1nc1BaU2xTVHp2a0pMZDBOT0E0VHU4Q2tDbjJBeFNmeUlHZE14TXFjRzhEd0gzTzIxWmJsWnNocDl3U2V5UjVzNVBxTlNUa1gvTzI2ek5oR1RLZU40ZTYvcVcxZXFtY3BzZXNEbWE1dnMwRUY4eDIrV0p3bis0WHRjZHhXRFZHOFNKVTBrdDBIM25JZXZUTExVcWo4VXlrK2wxd1cvSmpTU0kwOFNsNU1vbllqZzNjcjJtZGd5QUpZWDlqaFp0cXFwb1gxWmV5UW5OUWt5Y1UvMmdDc2xIMnFTQ3lrMjFjNmxqbzhFWEFiekRPNHQ4eUdlSG14ZSt2cDZ3QnkzZVVKYlY5VEs4VldQWXpzai9iVkpCZUdVcjdteHNBR3FNYStvMEVBQ1pDYTJleENDbWNnZWlFcEpMZkVKT2cxa3pFR0tNNVI4Vmhsdz09
01-27-2020 @ 04:12:18 -     [Info] $this->api_pub            = bXZuV0dFUitObXJqbnpKVlFMT2xFaVZ2YjlBb3Zwdkx4Y1JrL0phWUZMYUx2SEVRN1RVbTNuYkxhaGFOaEdlalRlVVdWaEVEMTdKMFEyRU1Qb1JaQmpOcW8vS3J4dUJrRDBCdG9hMjZieDAwZXJ6WnJsYlk2d0VEMnFjK3owaEtBd1MwZDk4MGY4VUszNjRKZHRCWkRoNUp1ZThFcFBqTlVWeGJIUTZWSGt5d1JqZkxFTUJINTZqbzlWSGVkWG55VmhqUVgxMjAzZnFNTzBIMm45U3VIY0phMlUvUjZjZi84ZEtiK1RFd0VONWJGY0hLZkZFK0tGVTYzQjZRUWdHTTIvYWpmdzc0bXhtNE4wTlBvQml6QnpSckQrd2gvYTBJY2dxakZWSkNlOVd2ekUrMHd1NlFSZGJyd2xPcnF5U2xoOWI0bWpPSk8zZ1hSeThmUytxTWNydC8rZ09xSzM5NUx2WUlTTlBSNVhaMVdNeUovcVB5UlBDYUtacVBYeWY3emdxK1NMS3UrQmdPd21BcG1uZEZBVEZvUElNTGhITUQ0Z2Vvc2t6WHRmU2xCRGI5VXFqcWFHbElLTDZic2dMd2FiODFJSGpqUXlkdUpzR1lIdjFIMGlGd2plNHREL3BzeGxmbDBvSlo3NzY4N25lc2IxYlpaV3RSRjBzN3FIaUZTODJIaXJuTEwzcHVoejZzMXlsdmpVRDA0NTIyQmZSbGljM0xqbG1VaVp2NHRZWnJGQjkxRFZGV3JUZkliWVZyUDl3bDdzbWwrNkErY1JleVVnaVRWTVNHV0dqeGtreGpkODVPNnkwVzhXRzRmUk56KzdSTUJ3OERxYXRvSUhib1prS0NDUlN4OS9hdGN0bXlQbDY2MituajU3VzNmM2NUVXFTRWR3MmdnVzdEd3pyMG12UjV5OWw1MWNqWFhMN1Q0eU1IcWFGRUd5STJkcnBTUndnMGpPTGc3TGVkQ1puNm9zVGxrV3R0ZkRMekNBSGQ2MXhKMTRlRU9xTEpmQ2tmdHN4VHBFejFhL24vbWp2bHAyTmo3N0hoV2YweUNKakFuY2hOMUd1OFA3TFZTK3lJbnpxdHZzdEkydjR0ZVZveUYvckRGYWdWdWMyTTk5WWFnNmR2aC9nelE1MVc4ekNBaWJKZmg4RkpvUTBJcGU1aHc3aWlKL2wwNUxQTloydk9tREF1dnZBdDVCeUIrYjdZM3ZTeEdBPT0=
01-27-2020 @ 04:12:18 -     [Info] $this->api_sin            = TfEa4cj6z2JhrPvnsSN6ioTsYvmc7vafLwh
01-27-2020 @ 04:12:18 -     [Info] $this->api_token          = YTNRbmJwZnRCODZrUHc0ZUdNc29qeituaWMwVERibk5LZ2ZoZkxTWXgyVmowQUJMclpyVmlDdHAxWElncmNXTU5pdks4TjFEL2h3MjBVbExHNjMxODZ6ZFRTNXZkR25KT1dlN1RieHNXL09KV0F1akVtVHhzbjFuNmpET0VUZ2ZuTW14bjhUWkVJQ1JsVVpTN3pxa3IzWGxBbnU4RHBnL1dGdEN3QU1PVjRhanpRazEzWUc1Y2M5dWthYzRpZnhQcG5hakZRTEtnWmcyRW9iK0Z0cHRGLzVGaFlXeXdJL3V2ak9ZQzhBUG9LUURKM09KUXRiaElUbmdYV0xuZHhaRHZLVDVHYXQwdmhPWXRtaTgwU2Y4ZTdPOWJCZFZFb0ZYR1VoRWx2OVlLNDJVYmFkVVlLKysyVmh3QUlJQUo2U0J3VEdqZG9EeW5qR2ZMRGM4Rmx5c1E5ZWY2T2tLS2E3Z2FVeThzWWZSWTc0UXlLM2xldUhiV2pMczh1KzcxQjdrMitGNGdYeGpaV0FLS0laWVZIWDRqbG9wY1ZCZmFGOGpHOEl3cTcyWXRTbnRQcjNmOTk1TjZOQmJucFFQVFlqRFRKbFJVRDNnbC9xZkd5NEcyeFozOWtrbFdsdFVHdkhxNnduRkhSV2pPQVVZVnlpMngrWkZBQ283TlhGb1Q3c1ZkS2VrRWhTRWFPT29qUjRjTFJiQ3dNVkJIMWQ2RmZQRFp0RGlVN01uNzVRRy9VMW0xNHdxcEZJK0JGTzRKUi9YcGVVQjFqMWJOOE1jVmFCUlMydmk4MkM3S3E3NnlQMjVEbzRSMWhMOWlzQzI4VUVKRk5Hc1g3dW9hbTVPamxhU0xTYXcwSXl3TElUK0xkd2N5SG1LNDZDOEh5QTIyc2JuVndtRFJGN0FyZzFnVXFrUC9QSjZDR3ltMGU1MVowQmdGMEl5TTR4UjBqbXZnOUcrQU9Pd1l0YWthdlNtUytJZm1xMEdWYWRoQ3VTVmlKRWdvQWJaK1cwMnUwWjhCcExEcHpRWkVoeXIxdU5vcjRqMXJDMVpNTkJNcmtZOHFIQ1JYMHhJRzZjdXl5NkdmVHNjaURaK0tsZlJwTkVZdTNIZHdQc3ZPb2RON29Ya0RIZ0tUS2pOdml2MjdKZzdGWXM0N3dLbkFHRGZuL1E9
01-27-2020 @ 04:12:18 -     [Info] $this->api_token_label    = WooCommerce - XXX - xxx xxx xxx
01-27-2020 @ 04:12:18 -     [Info] $this->api_url        = https://btcpayjungle.com/
01-27-2020 @ 04:12:18 -     [Info] Entered class level btcpay_decrypt...
01-27-2020 @ 04:12:18 -     [Warning] In btcpay_decrypt: data appears to have already been decrypted. Strict base64 check failed.
01-27-2020 @ 04:12:18 -     [Info] Leaving class level btcpay_decrypt...
01-27-2020 @ 04:12:18 -     [Info] Private Key decrypted successfully.
01-27-2020 @ 04:12:18 -     [Info] Entered class level btcpay_decrypt...
01-27-2020 @ 04:12:18 -     [Warning] In btcpay_decrypt: data appears to have already been decrypted. Strict base64 check failed.
01-27-2020 @ 04:12:18 -     [Info] Leaving class level btcpay_decrypt...
01-27-2020 @ 04:12:18 -     [Info] Public Key decrypted successfully.
01-27-2020 @ 04:12:18 -     [Info] Entered class level btcpay_decrypt...
01-27-2020 @ 04:12:18 -     [Warning] In btcpay_decrypt: data appears to have already been decrypted. Strict base64 check failed.
01-27-2020 @ 04:12:18 -     [Info] Leaving class level btcpay_decrypt...
01-27-2020 @ 04:12:18 -     [Info] API Token decrypted successfully.
01-27-2020 @ 04:12:18 -     [Info] Transaction speed is now set to: medium
01-27-2020 @ 04:12:18 -     [Info] Plugin is valid for use.
01-27-2020 @ 04:12:18 -     [Info] The plugin is ok to use.
01-27-2020 @ 04:12:21 - BTCPay Woocommerce payment plugin object constructor called. Plugin is v3.0.10 and server is PHP v7.0
01-27-2020 @ 04:12:21 -     [Info] $this->api_key            = SGpQWTBoSExIYnJPT2NEM2ZvNUdYb0t6WldVUUNyOVAwVGgyTU9wNk5ET3JxeFhQQW1xRm5Zb3pZTGJjbUw2NWd5ZXZzRjdRR2E1Sm1nc1BaU2xTVHp2a0pMZDBOT0E0VHU4Q2tDbjJBeFNmeUlHZE14TXFjRzhEd0gzTzIxWmJsWnNocDl3U2V5UjVzNVBxTlNUa1gvTzI2ek5oR1RLZU40ZTYvcVcxZXFtY3BzZXNEbWE1dnMwRUY4eDIrV0p3bis0WHRjZHhXRFZHOFNKVTBrdDBIM25JZXZUTExVcWo4VXlrK2wxd1cvSmpTU0kwOFNsNU1vbllqZzNjcjJtZGd5QUpZWDlqaFp0cXFwb1gxWmV5UW5OUWt5Y1UvMmdDc2xIMnFTQ3lrMjFjNmxqbzhFWEFiekRPNHQ4eUdlSG14ZSt2cDZ3QnkzZVVKYlY5VEs4VldQWXpzai9iVkpCZUdVcjdteHNBR3FNYStvMEVBQ1pDYTJleENDbWNnZWlFcEpMZkVKT2cxa3pFR0tNNVI4Vmhsdz09
01-27-2020 @ 04:12:21 -     [Info] $this->api_pub            = bXZuV0dFUitObXJqbnpKVlFMT2xFaVZ2YjlBb3Zwdkx4Y1JrL0phWUZMYUx2SEVRN1RVbTNuYkxhaGFOaEdlalRlVVdWaEVEMTdKMFEyRU1Qb1JaQmpOcW8vS3J4dUJrRDBCdG9hMjZieDAwZXJ6WnJsYlk2d0VEMnFjK3owaEtBd1MwZDk4MGY4VUszNjRKZHRCWkRoNUp1ZThFcFBqTlVWeGJIUTZWSGt5d1JqZkxFTUJINTZqbzlWSGVkWG55VmhqUVgxMjAzZnFNTzBIMm45U3VIY0phMlUvUjZjZi84ZEtiK1RFd0VONWJGY0hLZkZFK0tGVTYzQjZRUWdHTTIvYWpmdzc0bXhtNE4wTlBvQml6QnpSckQrd2gvYTBJY2dxakZWSkNlOVd2ekUrMHd1NlFSZGJyd2xPcnF5U2xoOWI0bWpPSk8zZ1hSeThmUytxTWNydC8rZ09xSzM5NUx2WUlTTlBSNVhaMVdNeUovcVB5UlBDYUtacVBYeWY3emdxK1NMS3UrQmdPd21BcG1uZEZBVEZvUElNTGhITUQ0Z2Vvc2t6WHRmU2xCRGI5VXFqcWFHbElLTDZic2dMd2FiODFJSGpqUXlkdUpzR1lIdjFIMGlGd2plNHREL3BzeGxmbDBvSlo3NzY4N25lc2IxYlpaV3RSRjBzN3FIaUZTODJIaXJuTEwzcHVoejZzMXlsdmpVRDA0NTIyQmZSbGljM0xqbG1VaVp2NHRZWnJGQjkxRFZGV3JUZkliWVZyUDl3bDdzbWwrNkErY1JleVVnaVRWTVNHV0dqeGtreGpkODVPNnkwVzhXRzRmUk56KzdSTUJ3OERxYXRvSUhib1prS0NDUlN4OS9hdGN0bXlQbDY2MituajU3VzNmM2NUVXFTRWR3MmdnVzdEd3pyMG12UjV5OWw1MWNqWFhMN1Q0eU1IcWFGRUd5STJkcnBTUndnMGpPTGc3TGVkQ1puNm9zVGxrV3R0ZkRMekNBSGQ2MXhKMTRlRU9xTEpmQ2tmdHN4VHBFejFhL24vbWp2bHAyTmo3N0hoV2YweUNKakFuY2hOMUd1OFA3TFZTK3lJbnpxdHZzdEkydjR0ZVZveUYvckRGYWdWdWMyTTk5WWFnNmR2aC9nelE1MVc4ekNBaWJKZmg4RkpvUTBJcGU1aHc3aWlKL2wwNUxQTloydk9tREF1dnZBdDVCeUIrYjdZM3ZTeEdBPT0=
01-27-2020 @ 04:12:21 -     [Info] $this->api_sin            = TfEa4cj6z2JhrPvnsSN6ioTsYvmc7vafLwh
01-27-2020 @ 04:12:21 -     [Info] $this->api_token          = YTNRbmJwZnRCODZrUHc0ZUdNc29qeituaWMwVERibk5LZ2ZoZkxTWXgyVmowQUJMclpyVmlDdHAxWElncmNXTU5pdks4TjFEL2h3MjBVbExHNjMxODZ6ZFRTNXZkR25KT1dlN1RieHNXL09KV0F1akVtVHhzbjFuNmpET0VUZ2ZuTW14bjhUWkVJQ1JsVVpTN3pxa3IzWGxBbnU4RHBnL1dGdEN3QU1PVjRhanpRazEzWUc1Y2M5dWthYzRpZnhQcG5hakZRTEtnWmcyRW9iK0Z0cHRGLzVGaFlXeXdJL3V2ak9ZQzhBUG9LUURKM09KUXRiaElUbmdYV0xuZHhaRHZLVDVHYXQwdmhPWXRtaTgwU2Y4ZTdPOWJCZFZFb0ZYR1VoRWx2OVlLNDJVYmFkVVlLKysyVmh3QUlJQUo2U0J3VEdqZG9EeW5qR2ZMRGM4Rmx5c1E5ZWY2T2tLS2E3Z2FVeThzWWZSWTc0UXlLM2xldUhiV2pMczh1KzcxQjdrMitGNGdYeGpaV0FLS0laWVZIWDRqbG9wY1ZCZmFGOGpHOEl3cTcyWXRTbnRQcjNmOTk1TjZOQmJucFFQVFlqRFRKbFJVRDNnbC9xZkd5NEcyeFozOWtrbFdsdFVHdkhxNnduRkhSV2pPQVVZVnlpMngrWkZBQ283TlhGb1Q3c1ZkS2VrRWhTRWFPT29qUjRjTFJiQ3dNVkJIMWQ2RmZQRFp0RGlVN01uNzVRRy9VMW0xNHdxcEZJK0JGTzRKUi9YcGVVQjFqMWJOOE1jVmFCUlMydmk4MkM3S3E3NnlQMjVEbzRSMWhMOWlzQzI4VUVKRk5Hc1g3dW9hbTVPamxhU0xTYXcwSXl3TElUK0xkd2N5SG1LNDZDOEh5QTIyc2JuVndtRFJGN0FyZzFnVXFrUC9QSjZDR3ltMGU1MVowQmdGMEl5TTR4UjBqbXZnOUcrQU9Pd1l0YWthdlNtUytJZm1xMEdWYWRoQ3VTVmlKRWdvQWJaK1cwMnUwWjhCcExEcHpRWkVoeXIxdU5vcjRqMXJDMVpNTkJNcmtZOHFIQ1JYMHhJRzZjdXl5NkdmVHNjaURaK0tsZlJwTkVZdTNIZHdQc3ZPb2RON29Ya0RIZ0tUS2pOdml2MjdKZzdGWXM0N3dLbkFHRGZuL1E9
01-27-2020 @ 04:12:21 -     [Info] $this->api_token_label    = WooCommerce - XXX - xxx xxx xxx
01-27-2020 @ 04:12:21 -     [Info] $this->api_url        = https://btcpayjungle.com/
01-27-2020 @ 04:12:21 -     [Info] Entered class level btcpay_decrypt...
01-27-2020 @ 04:12:21 -     [Warning] In btcpay_decrypt: data appears to have already been decrypted. Strict base64 check failed.
01-27-2020 @ 04:12:21 -     [Info] Leaving class level btcpay_decrypt...
01-27-2020 @ 04:12:21 -     [Info] Private Key decrypted successfully.
01-27-2020 @ 04:12:21 -     [Info] Entered class level btcpay_decrypt...
01-27-2020 @ 04:12:21 -     [Warning] In btcpay_decrypt: data appears to have already been decrypted. Strict base64 check failed.
01-27-2020 @ 04:12:21 -     [Info] Leaving class level btcpay_decrypt...
01-27-2020 @ 04:12:21 -     [Info] Public Key decrypted successfully.
01-27-2020 @ 04:12:21 -     [Info] Entered class level btcpay_decrypt...
01-27-2020 @ 04:12:21 -     [Warning] In btcpay_decrypt: data appears to have already been decrypted. Strict base64 check failed.
01-27-2020 @ 04:12:21 -     [Info] Leaving class level btcpay_decrypt...
01-27-2020 @ 04:12:21 -     [Info] API Token decrypted successfully.
01-27-2020 @ 04:12:21 -     [Info] Transaction speed is now set to: medium
01-27-2020 @ 04:12:21 -     [Info] Plugin is valid for use.
01-27-2020 @ 04:12:21 -     [Info] The plugin is ok to use.
01-27-2020 @ 04:12:21 -     [Info] Entered process_payment() with order_id = 80...
01-27-2020 @ 04:12:21 -     [Info] Generating payment form for order 80. Notify URL: http://XXX/wc-api/WC_Gateway_BtcPay/
01-27-2020 @ 04:12:21 -     [Info] Changing order status to: wc-pending
01-27-2020 @ 04:12:21 -     [Info] Changed order status result
01-27-2020 @ 04:12:21 -     [Info] The variable thanks_link = http://XXX/checkout/order-received/80/?key=wc_order_pQ3bPjdz163GQ...
01-27-2020 @ 04:12:21 -     [Info] The variable redirect_url = http://XXX/checkout/order-received/80/?key=wc_order_pQ3bPjdz163GQ...
01-27-2020 @ 04:12:21 -     [Info] Notification URL is now set to: http://XXX/wc-api/WC_Gateway_BtcPay/...
01-27-2020 @ 04:12:21 -     [Info] The variable currency_code = EUR...
01-27-2020 @ 04:12:21 -     [Info] Set url to https://btcpayjungle.com/
01-27-2020 @ 04:12:21 -     [Info] Key and token empty checks passed.  Parameters in client set accordingly...
01-27-2020 @ 04:12:21 -     [Info] Invoice object created successfully...
01-27-2020 @ 04:12:21 -     [Info] Item object created successfully...
01-27-2020 @ 04:12:21 -     [Info] Attempting to generate invoice for 80...
01-27-2020 @ 04:12:23 -     [Info] Call to generate invoice was successful: {"facade":"pos/invoice","data":{"url":"https://btcpayjungle.com/invoice?id=Aw6XgCYLs6xuPyWxxFCbzw","posData":null,"status":"new","btcPrice":"0.00001410","btcDue":"0.00001410","cryptoInfo":[{"cryptoCode":"BTC","paymentType":"BTCLike","rate":7806.074,"exRates":{"EUR":0.0},"paid":"0.00000000","price":"0.00001410","due":"0.00001410","paymentUrls":{"BIP21":"bitcoin:bc1qq96lz394l2qcs99wc0qxnl22xdsee2ljfpfls8?amount=0.0000141","BIP72":null,"BIP72b":null,"BIP73":null,"BOLT11":null},"address":"bc1qq96lz394l2qcs99wc0qxnl22xdsee2ljfpfls8","url":"https://btcpayjungle.com/i/BTC/Aw6XgCYLs6xuPyWxxFCbzw","totalDue":"0.00001410","networkFee":"0.00000000","txCount":0,"cryptoPaid":"0.00000000","payments":[]}],"price":0.11,"currency":"EUR","exRates":{"EUR":0.0},"buyerTotalBtcAmount":null,"itemDesc":null,"itemCode":null,"orderId":"80","guid":"a64f4fa9-db63-4690-956e-3d0e9321be7e","id":"Aw6XgCYLs6xuPyWxxFCbzw","invoiceTime":1580116342000,"expirationTime":1580116402000,"currentTime":1580116343506,"lowFeeDetected":false,"btcPaid":"0.00000000","rate":7806.074,"exceptionStatus":false,"paymentUrls":{"BIP21":"bitcoin:bc1qq96lz394l2qcs99wc0qxnl22xdsee2ljfpfls8?amount=0.0000141","BIP72":null,"BIP72b":null,"BIP73":null,"BOLT11":null},"refundAddressRequestPending":false,"buyerPaidBtcMinerFee":null,"bitcoinAddress":"bc1qq96lz394l2qcs99wc0qxnl22xdsee2ljfpfls8","token":"Ja9P4gVBFLvi2EjnZP4gTS","flags":{"refundable":false},"paymentSubtotals":{"BTC":1410.0},"paymentTotals":{"BTC":1410.0},"amountPaid":0,"minerFees":{"BTC":{"satoshisPerByte":9.0,"totalFee":0.0}},"exchangeRates":{"BTC":{"EUR":0.0}},"supportedTransactionCurrencies":{"BTC":{"enabled":true}},"addresses":{"BTC":"bc1qq96lz394l2qcs99wc0qxnl22xdsee2ljfpfls8"},"paymentCodes":{"BTC":{"BIP21":"bitcoin:bc1qq96lz394l2qcs99wc0qxnl22xdsee2ljfpfls8?amount=0.0000141","BIP72":null,"BIP72b":null,"BIP73":null,"BOLT11":null}},"buyer":{"name":"","address1":"","address2":"","locality":null,"region":null,"postalCode":null,"country":null,"phone":null,"email":"test@testmail.com"}}}
01-27-2020 @ 04:12:24 -     [Info] BTCPay invoice assigned Aw6XgCYLs6xuPyWxxFCbzw
01-27-2020 @ 04:12:24 -     [Info] Leaving process_payment()...
`

**Comment by pavlenex** [comment]
Try disabling woocommerce admin plugin, it causes conflicts that mess with order statuses.

**Comment by pavlenex** [comment]
Although apparently the compatibility is fixed by  @pieterpoorthuis in #39 so it may not be that, still worth trying out.

**Comment by ThoKolKol** [comment]
> Try disabling woocommerce admin plugin, it causes conflicts that mess with order statuses.

I dont have this plugin. I just have Wordpress with WooCommerce and plugin for selling serial numbers.

**Comment by pavlenex** [comment]
Interesting, you're right it's broken. Can you try installing https://wordpress.org/plugins/woocommerce-admin/ and then see if it works? I'm investigating what may cause this.

**Comment by ThoKolKol** [comment]
Okay, I'll try in a moment

**Comment by pavlenex** [comment]
Was unable to retrive logs for particular failed order, the closes I found was

```
2020-01-27T11:20:20+00:00 CRITICAL Uncaught Exception: The BTCPay payment plugin was called to process an IPN message but could not retrieve the order details for order_id 6776. Cannot continue! in /var/www/html/wp-content/plugins/btcpay-for-woocommerce/class-wc-gateway-btcpay.php:983
Stack trace:
#0 /var/www/html/wp-includes/class-wp-hook.php(288): WC_Gateway_BtcPay->ipn_callback('')
#1 /var/www/html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters('', Array)
#2 /var/www/html/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#3 /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-api.php(148): do_action('woocommerce_api...')
#4 /var/www/html/wp-includes/class-wp-hook.php(288): WC_API->handle_api_requests(Object(WP))
#5 /var/www/html/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#6 /var/www/html/wp-includes/plugin.php(544): WP_Hook->do_action(Array)
#7 /var/www/html/wp-includes/class-wp.php(387): do_action_ref_array('parse_request', Array)
#8 /var/www/html/wp-includes/class-wp.php(729): WP->pa in /var/www/html/wp-content/plugins/btcpay-for-woocommerce/class-wc-gateway-btcpay.php on line 983
```

**Comment by ThoKolKol** [comment]
With Woocommerce Admin it's the same, status doesn't change

**Comment by pieterpoorthuis** [comment]
If you use a plugin that changes the order numbers, you need to use a filter. E.g. I'm using the sequential order number plugin and need the following in functions.php:
```
// to make the Btcpay plugin work
// https://docs.woocommerce.com/document/sequential-order-numbers/?_ga=2.132910925.256149075.1576848725-369569876.1567413704#faq-compatibility
add_filter( 'woocommerce_order_id_from_number', 'order_number_to_order_id' );

function order_number_to_order_id($order_number) {
	return wc_seq_order_number_pro()->find_order_by_order_number( $order_number );
}
```

**Comment by ThoKolKol** [comment]
I dont this sort of plugin.

I did a completely new installation of Wordpress. Unfortunately, but the problem is the same. Only Woocommerce + BTCPay plugin, and there is no order status update. What's happening?

**Comment by pieterpoorthuis** [comment]
Which version of the plugin are you running? If I'm looking at https://github.com/btcpayserver/woocommerce-plugin/blob/master/src/class-wc-gateway-btcpay.php, line 983 is a blank line.

It seems that the composer version is outdated (3.0.5), because the newest version is 3.0.10, as available on https://wordpress.org/plugins/btcpay-for-woocommerce/#installation

**Comment by pieterpoorthuis** [comment]
Although your logs show version 3.0.10, the plugin code definitely is not most recent. Looks like a mixture of old & new code.

Can you explain in details how you installed the Btcpay plugin? Did you use the wordpress plugin UI, or by downloading a release from github, or ..? Did you install previous versions first?

**Comment by ThoKolKol** [comment]
I downloaded plugins (BTCpayserver plugin and Woocommerce) two days ago from wordpress plugin site. I downloaded zip files, unpack and upload into plugins directory - typical stuff.

Now im reinstalling my VPS and i try it on clean server

**Comment by pieterpoorthuis** [comment]
Can you try to install using the wordpress plugin UI? (dashboard -> plugins -> search -> btcpay -> install)?
Maybe there's a misalignment between different download options.

**Comment by ThoKolKol** [comment]
Ok i'll try

**Comment by pavlenex** [comment]
On my end, I just updated the plugin from WP, and it `only` works now when Woo for Admin is active. Really strange.

@pieterpoorthuis if you want to troubleshoot I can provide you with an access to store.btcpayserver.org where I replicated this. DM me on[ BTCPay Server Mattermost Chat](https://chat.btcpayserver.org/) if you want to take a look.

**Comment by pavlenex** [comment]
Unfortunately I'm unable to replicate this anymore. 

It happened after I updated the plugin and disabled woocommerce for admin. Everything seems to work afterwards. No logs whatsoever.

BTCPay For Woo 3.0.10
WordPress:  5.3.2	
WooCommerce 3.9.0

**Comment by ThoKolKol** [comment]
Hello everyone,

It started working after reinstalling the server. Unfortunately, I don't know what the reason was. Maybe some network configuration problem. But unfortunately I have another problem, some orders do not redirect to the payment gateway, only display a white page (the order appears in the panel, but it cannot be paid). (I will create a new thread).

**Comment by NicolasDorier** [comment]
I will check if by any chance I did not messed up the update. The fact code is not most recent is strange.

**Comment by NicolasDorier** [comment]
I was not creating releases on github, so I just did:

https://github.com/btcpayserver/woocommerce-plugin/releases/tag/v3.0.10

But the plugin is correctly on the latest version in the store.

**Comment by pavlenex** [comment]
Re-opening this as there are 2-3 people who're reporting they are still having issues. 

If you're having issues, please post logs here.

**Comment by pavlenex** [comment]
I've been troubleshooting the issue with people who reported it and it turns out it's nothing on our end, in both cases it was something else.

Case 1: User used WordFence security plugin that too aggresively blocked calls from BTCPay Server, providing errors like:
```

Date | Message
-- | --
2/19/2020 4:42:47 PM | Creation of invoice starting
2/19/2020 4:42:48 PM | BTC_USD: The rating rule is coinaverage(BTC_USD)
2/19/2020 4:42:48 PM | BTC_USD: The evaluated rating rule is 9635.692
2/19/2020 4:42:48 PM | BTC (On-Chain): Payment method details creation took 4 milliseconds
2/19/2020 4:42:48 PM | BTC (Off-Chain): Payment method details creation took 175 milliseconds
2/19/2020 4:42:48 PM | Saving invoice took 144 milliseconds
2/19/2020 4:42:48 PM | Invoice 55UGWX8qM1RqfXYW77kKAW new event: invoice_created (1001)
2/19/2020 4:42:49 PM | Error while sending IPN (1001 invoice_created): Unexpected return code: 503
2/19/2020 4:48:52 PM | Invoice 55UGWX8qM1RqfXYW77kKAW new event: invoice_receivedPayment (1002)
2/19/2020 4:48:52 PM | Invoice status is paid
2/19/2020 4:48:52 PM | Invoice 55UGWX8qM1RqfXYW77kKAW new event: invoice_paidInFull (1003)
2/19/2020 4:48:53 PM | Error while sending IPN (1002 invoice_receivedPayment): Unexpected return code: 503
2/19/2020 4:48:54 PM | Error while sending IPN (1003 invoice_paidInFull): Unexpected return code: 503
2/19/2020 4:48:54 PM | Error while sending IPN (1003 invoice_paidInFull): Unexpected return code: 503
2/19/2020 4:52:49 PM | Error while sending IPN (1001 invoice_created): Unexpected return code: 503
2/19/2020 4:58:54 PM | Error while sending IPN (1002 invoice_receivedPayment): Unexpected return code: 503
2/19/2020 4:58:55 PM | Error while sending IPN (1003 invoice_paidInFull): Unexpected return code: 503
2/19/2020 4:58:55 PM | Error while sending IPN (1003 invoice_paidInFull): Unexpected return code: 503
2/19/2020 5:02:50 PM | Error while sending IPN (1001 invoice_created): Unexpected return code: 503
```
Disabling the plugin solved the issue.

Case 2: User used the plugin with Tor and the issue did not seem related to order statuses at all. Here's what he reported:

> I run on tor / onion. Run woocommerce and btcpayserver in one machine. And the solution is just add the btcpayserver address and woocommerce address in onion to /etc/hosts

I've done several tests and indeed the plugin works, so I am closing the issue.
