### ISSUE TITLE
What Url incl. Pairing Code to enter at Woocommerce to connect with BTCPay?

### ISSUE THREAD

**Issue by conyisland** [btcpayserver/woocommerce-plugin#41]
I am no Developer i am just a User that wants to integrate BTCPay into my Onlineshop/Checkout Page as a Paying Method. I have a Question according the Url-Structure that must be entered at Woocommerce/Paying Methods/BTCPay. I have the BTCPayServer as Plug In (installed in my Store Template). Now i have to create the API-Token and enter a Url and a Pairing Code. I created the Pairing Code in my Store Account at btcpayserver.org/Access Token. But now i am stuck in, how the URL has to look like, do i also have to enter my ending like mydomain.com or .net etc. and does the Hyphen have to be there too? Could somebody show me where my Pairing Code should be written?  Confusing is, that they show a sample-Url saying "https://your-btcpay.com" and underneath of that they say "please enter BTCpay Url first". So it is realy hard to say what sequenz it should have  and where the Pairing Code has to be written.

**Comment by pavlenex** [comment]
Replied on Mattermost already 
https://docs.btcpayserver.org/integrations/woocommerce
