### ISSUE TITLE
Wordpress 5.4.1: Error processing checkout. Please try again.

### ISSUE THREAD

**Issue by dinucci** [btcpayserver/woocommerce-plugin#46]
Hello, I'm testing BTCPay WooCommerce plugin and it seems it's not working with Wordpress 5.4.1.

I'm running Wordpress 5.4.1 with PHP7.4, Nginx and MariaDB on an Ubuntu 18.04 VPS.

When I place an order and click on "Proceed to BTCPay" I get a warning message saying: "Error processing checkout. Please try again."

I don't know where to get more details.

Best regards,
Alejandro

**Comment by pavlenex** [comment]
Hi, you need to connect your wallet to a store inside btcpay server for checkout to work. Can you confirm you did that? https://docs.btcpayserver.org/getting-started/connectwallet

**Comment by dinucci** [comment]
Yes, I did that but thanks I'll double-check!

Blockchain Sync is 62%, I'll wait until is 100% and then maybe regenerate the API keys.

**Comment by pavlenex** [comment]
You cannot generate an invoice unless blockchain is fully synced. 

That's probably the issue here.

**Comment by dinucci** [comment]
That was spot on, today the blockchain finished syncing and I can confirm it works just fine
Wordpress 5.4.1 + WooCommerce 4.10 + BTCPay 3.0.10
(Ubuntu Server 18.04, Nginx, PHP 7.4, MariaDB)

Thanks for your time!
