### ISSUE TITLE
Warning message on the WordPress plugin page

### ISSUE THREAD

**Issue by l33d4n** [btcpayserver/woocommerce-plugin#48]
WordPress has made some major updates over the last six months, is it possible to check if the plugin is compatible with the latest version and update it on the plugin page?

**Warning message on the WordPress plugin page:**

> **This plugin hasn’t been tested with the latest 3 major releases of WordPress. It may no longer be maintained or supported and may have compatibility issues when used with more recent versions of WordPress.**

URL: https://wordpress.org/plugins/btcpay-for-woocommerce/

## Screenshot
![image](https://user-images.githubusercontent.com/8020386/90208472-85e3bf00-de1b-11ea-9214-d5e2523b23d3.png)

**Comment by NicolasDorier** [comment]
we should try it. That said nobody complained and this plugin is rather used, so it should work.

**Comment by l33d4n** [comment]
If it works then it's great, but there is a way to update it on the WordPress website to avoid displaying this message? This seems stressful for new users.

**Comment by l33d4n** [comment]
Closed by @NicolasDorier 

https://github.com/btcpayserver/woocommerce-plugin/commit/16762916ef2a671fc08bbb86dcd86c17e29f852a
