### ISSUE TITLE
Use https on pairing 

### ISSUE THREAD

**Issue by britttttk** [btcpayserver/woocommerce-plugin#49]
Some users are having issues pairing properly. If woocommerce needs https, it should be used automatically or give warning on the input. Issue context [here](https://github.com/btcpayserver/btcpayserver/issues/797#issuecomment-680972914).

**Comment by NicolasDorier** [comment]
HTTPS should not need to reach btcpay from woocommerce.

**Comment by NicolasDorier** [comment]
If I understand the context, the user input http instead of https. Nothing we can do here, there are valid reasons to use HTTP (BTCPay and Woocommerce are on an intenral network)
