### ISSUE TITLE
The currency code "XLM" is not supported

### ISSUE THREAD

**Issue by MatapaCoin** [btcpayserver/woocommerce-plugin#68]
hi, i've got a store on woocommerce that sells tokens but i would like to do it using Stellar XLM.
For this, I have added the following code in the functions.php file of the main theme: ( I have also tried it with the plugin _All Currencies for WooCommerce_ and the same thing happens )

add_filter( 'woocommerce_currencies', 'add_custom_currency' );
function add_custom_currency( $wc_currency ) {
     $wc_currency['XLM'] = __( 'XLM Stellar', 'woocommerce' );
     return $wc_currency;
}
add_filter('woocommerce_currency_symbol', 'add_custom_currency_symbol', 10, 2);
function add_custom_currency_symbol( $custom_currency_symbol, $custom_currency ) {
     switch( $custom_currency ) {
         case 'XLM': $custom_currency_symbol = 'XLM'; break;
     }
     return $custom_currency_symbol;

}

![image](https://user-images.githubusercontent.com/87453472/140552564-1ed254de-8d64-4b1e-ad20-a2280f1c6b70.png)

I update the woocomerce settings page and I can see the new currency, but in the payment settings, the plugin is automatically disabled

![image](https://user-images.githubusercontent.com/87453472/140552466-3eff316a-0a3e-4cab-8214-fcce46bd8770.png)

****Logs ****

11-05-2021 @ 12:41:28 -     [Error] In is_valid_for_use: The currency code "XLM" is not supported.
11-05-2021 @ 12:41:28 -     [Info] The plugin is NOT valid for use!

- BTCPay Server Version:    v1.3.1.0 (altcoins)
- Deployment Method:      Manual and Third-Party-host
- Browser:                  Chrome

Additional context

It works fine with the "pay button", but I require it to work with the woocomerce store.

Thanks! 
Ruddy

**Comment by Kukks** [comment]
Xlm is not supported by btcpay officially or unofficially so this is impossible.

**Comment by pavlenex** [comment]
@Kukks It seems they're using a different plugin than ours?

**Comment by MatapaCoin** [comment]
> Xlm is not supported by btcpay officially or unofficially so this is impossible.

and yet using the payment button it works!
![image](https://user-images.githubusercontent.com/87453472/140565963-33ce8c12-306a-4d26-8591-4d27fcac1013.png)

**Comment by pavlenex** [comment]
@MatapaCoin No, this is btc just priced in XML, which is weird, but I guess XML is supported currency list

**Comment by NicolasDorier** [comment]
> but I guess XML is supported currency list

@MatapaCoin @pavlenex we do not have such a list. We support in the invoice whichever currency is supported by the rating source. If he selected say Kraken and Kraken have a BTC/XML pair, then this will be used.

**Comment by NicolasDorier** [comment]
I actually close this issue because we don't have a currency field in our plugin.

**Comment by NicolasDorier** [comment]
@MatapaCoin can you try modifying this line `https://github.com/btcpayserver/woocommerce-plugin/blob/master/src/class-wc-gateway-btcpay.php#L823` to

```
$invoice->setCurrency(new \Bitpay\CurrencyUnrestricted($currency));
```

**Comment by NicolasDorier** [comment]
Try to change this line https://github.com/btcpayserver/woocommerce-plugin/blob/master/src/class-wc-gateway-btcpay.php#L290 to 

`new \Bitpay\CurrencyUnrestricted(get_woocommerce_currency());`

**Comment by NicolasDorier** [comment]
I normally fixed this line with 3.0.15

**Comment by NicolasDorier** [comment]
@MatapaCoin it worked?

**Comment by MatapaCoin** [comment]
> @MatapaCoin it worked?

Hi Nicolas, thanks for asking. yes it works, the plugin is not disabled when I set the XLM as currency, thanks for that, but i think the error may come now from woocommerce. (now, I will analyze in more detail the problem with woocommerce.)

Log:

11-08-2021 @ 11:34:10 -     [Info] Leaving class level btcpay_decrypt...
11-08-2021 @ 11:34:10 -     [Info] API Token decrypted successfully.
11-08-2021 @ 11:34:10 -     [Info] Transaction speed is now set to: default
11-08-2021 @ 11:34:10 -     [Info] Plugin is valid for use.
11-08-2021 @ 11:34:10 -     [Info] The plugin is ok to use.

![image](https://user-images.githubusercontent.com/87453472/140770367-7b751498-3079-4c70-8a2b-ef28264a3d86.png)

Thanks
Ruddy
