### ISSUE TITLE
Make the plugin compatible to be added to WP plugin directory

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/woocommerce-plugin#7]
Esky33 tried to submit this fork to the official Wordpress plugin directory but they posponed the addition because of some violations of their guidelines. 
For reference see the thread here: https://forkbitpay.slack.com/archives/C6PSCRFAM/p1530048285000716

Summarized the following need to be fixed (detailed feedback at the bottom):
- [ ] Update Readme according to guidelines
- [ ] Remove/refactor update checker to use their preferred way (no phone home or to Github allowed)
- [ ] Sanitize direct handling of possible insecure variables returned by API via `$_POST`
- [ ] this means make sure to follow their guidelines

**I suggested the following additional changes [here](https://forkbitpay.slack.com/archives/C6PSCRFAM/p1530045748000529):**
To put a BTCPay version of the plugin into WP directory I see the following things todo:
- [ ] replace all mentions of BitPay (esp. filenames/classnames/..) with BTCPay to avoid name collisions and broken sites when both installed
- [ ] do that by keeping the credits for BitPay and make that clear that we forked from them
- [ ] (optionally) refactor it so that it works without the forked bitpay php-client library but use existing `Customnet` class to avoid maintaining another fork for now 

# Full feedback from WP team:

Thank you for uploading BTCPay for WooCommerce to the WordPress Plugin Directory. We will review your submission as soon as possible and send you a follow up email with the results.

Your plugin has been given the initial slug of btcpay-for-woocommerce, however this is subject to change based on the results of your review.

If there is a problem with this submission, such as an incorrect display name or slug, please reply to this email and let us know. In most cases, we can correct errors as long as the plugin has not yet been approved. Please do not submit your plugin multiple times in an attempt to correct the issue, just email us.

Remember to read the developer guidelines: https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/

Please make sure to follow our official blog: https://make.wordpress.org/plugins/

---

There are issues with your plugin code.

Please read this ENTIRE email, address all listed issues, and reply to this email with your corrected code attached (or linked). It is required for you to read and reply to these emails, and failure to do so will result in significant delays with your plugin being accepted.

Remember in addition to code quality, security and functionality, we require all plugins adhere to our guidelines. If you have not yet, please read them:

* https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/

You will not be able to submit another plugin while this one is being reviewed, so please read the email carefully. We know it can be long, but you must follow the directions at the end as not doing so will result in your review being delayed. (bearbeitet)

## Including your own update checker

Please remove the checks you have in your plugin to provide for updates from Github.

We do not permit plugins to phone home to other servers for updates, as we are providing that service for you with WordPress.org hosting. One of our guidelines is that you actually use our hosting, so we need you to remove that code.

## Please sanitize, escape, and validate your POST calls 

When you include POST/GET/REQUEST/FILE calls in your plugin, it's important to sanitize, validate, and escape them. The goal here is to prevent a user from accidentally sending trash data through the system, as well as protecting them from potential security issues. 

SANITIZE: Data that is input (either by a user or automatically) must be sanitized. This lessens the possibility of XSS vulnerabilities and MITM attacks where posted data is subverted.

VALIDATE: All data should be validated as much as possible. Even when you sanitize, remember that you don’t want someone putting in ‘dog’ when the only valid values are numbers.

ESCAPE: Data that is output must be escaped properly, so it can't hijack admin screens. There are many esc_*() functions you can use to make sure you don't show people the wrong data.

To help you with this, WordPress comes with a number of sanitization and escaping functions. You can read about those here: https://developer.wordpress.org/plugins/security/securing-input/

Remember: You must use the MOST appropriate functions for the context. If you’re sanitizing email, use sanitize_email(), if you’re outputting HTML, use esc_html(), and so on.

Clean everything, check everything, escape everything, and never trust the users to always have input sane data. 

Some examples from your plugin:
```
$order_states = $_POST[ $this->plugin_id . $this->id . '_order_states' ];
```
and
```
               if (filter_var($_POST[ $this->plugin_id . $this->id . '_' . $key ], FILTER_VALIDATE_URL) !== false) {
                   $url = $_POST[ $this->plugin_id . $this->id . '_' . $key ];
```

You want to use esc_url() or esc_url_raw() there - it's more robust.

## Incomplete Readme 

Plugins that send data to other servers, call js from other servers, and/or require passwords and APIs to function are required to have a full and complete Readme so we can make sure you're providing the users with all the information they need before they install your plugin. Our goal with this is to make sure everyone knows what they're installing and what they need to do before they install it. No surprises. 

This is especially important if your plugin is making calls back to your own servers. For the most part, we do not permit offloading of images or code, however in the case where you are providing a service (like Disqus or Akismet or Twitter), we permit it. The catch is you have to actually explain this to the layman in your read me, so they know where data is going.

Your read me MUST validate per http://wordpress.org/plugins/about/validator/ or we will reject it. Keep in mind, we don't want to see a readme.MD. Among other things, the formatting for markup is different, and the filetype isn't read by our system. (And if you're thinking "Hey, I did submit a read me!" then it's likely we felt it wasn't informative enough.)

Please create your readme one based on this: https://wordpress.org/plugins/readme.txt

Please send a link so the completed plugin can be downloaded. Alternately you can reply to this and send a .zip file. Note: We would like you to send the whole plugin, not just the read me, as we will re-review your entire code as a whole.

**Comment by NicolasDorier** [comment]
Thanks for trying this. This is awesome. We should probably make a separate branch which comply with woocommerce guideline while keeping our current master working correctly.

I am a bit busy these days so I won't be able to concentrate on this, but I can easily test.

**Comment by Eskyee** [comment]
WP Plugin admin team:
they did not mention replace all mentions of BitPay,  
I think thats not whats stopping our listing.
they care more about Please sanitize, escape, and validate your POST calls in the PHP,

need some PHP expert on this to check the code.

as for the Read Me part, that part  I understand, and will post tonight here what I think it should look like to pass validation.  happy to help out anyway possible to get this on the WP plugin listing. ASAP

**Comment by Eskyee** [comment]
I done check to the Wordpress readme 
To validate , a few weeks ago. I add here.

its a quick rough, to see what was needed.

WordPress Plugin readme.txt Validator
Warnings:
* Contributors field is missing.
* One or more contributors listed were ignored. Contributors field should only contain WordPress.org usernames.
Notes:
* No == Upgrade Notice == section was found
* No donate link was found


1 BTCPay needs a Wordpress User Account to be included in Contributors.
2 Upgrade notice to be included, this upgrade has to come from the Wordpress plugin directory
3 donate link needed for btcpay server


The Readme code looks like this:

=== btcpay-for-woocommerce ===
Contributors: btcpay esky33
Tags: bitcoin, payments, btcpay, cryptocurrency, payment
Requires at least: 4.3.1
Tested up to: 4.9.5
Requires PHP: 5.5
Stable tag: 2.2.24
License: MIT License (MIT)
License URI: https://opensource.org/licenses/MIT

btcpay allows you to accept bitcoin payments on your WooCommerce store.

== Description ==

Use btcpay's plugin to accept Bitcoin payments from customers anywhere on earth.

Key features:

* Support all bitcoin wallets that support payment protocol
* Price in your local currency, let customers pay with bitcoin
* Have an overview of all your bitcoin payments in your btcpay merchant dashboard at https://btcpay.com
* Refund your customers in bitcoin in your btcpay merchant dashboard at https://btcpay.com

= Installation =
This plugin requires Woocommerce. Please make sure you have Woocommerce installed.

1. Get started by signing up for a [btcpay merchant account.](https://btcpay-server-testnet.azurewebsites.net/Account/Register)
1. Download the latest version of the btcpay plugin from the [Wordpress site.](https://downloads.wordpress.org/plugin/btcpay-for-woocommerce.2.2.24.zip)
1. Install the latest version of the btcpay plugin for Woocommerce:
	* Navigate to your WordPress Admin Panel and select Plugins > Add New > Upload Plugin.
	* Select the downloaded plugin and click "Install Now".
	* Select "Activate Plugin" to complete installation.

= Connecting btcpay and Woocommerce =
After you have installed the btcpay plugin, you can configure the plugin:

1. Create a btcpay pairing code in your btcpay merchant dashboard:
	* Login to your [btcpay merchant account](https://btcpay.com/dashboard/login/) and select Payment Tools -> Manage API Tokens -> Add New Token -> Add Token
	* Copy the 7 character pairing code
2. Log in to your WordPress admin panel and select "Plugins" -> "Settings" link for the btcpay plugin.
	* Paste the 7 character pairing code into the "Pairing Code" field in your btcpay plugin and click "Find"
	* Click "Save changes" at the bottom

Pairing codes need to be used once and are only valid for 24 hours. If a code expires before you get to use it, you can always create a new one and pair with it.

Nice work! Your customers will now be able to check out with bitcoin on your WordPress site.

== Frequently Asked Questions ==

= How do I pay a btcpay invoice? =
You can pay a btcpay invoice with a Bitcoin wallet. You can either scan the QR code or copy/paste the payment link in your Bitcoin wallet.

More information about paying a btcpay invoice can be found [here.](https://support.btcpay.com/hc/en-us/articles/203281456-How-do-I-pay-a-btcpay-invoice-)

= Does btcpay have a test environment? =
btcpay allows you to create a test merchant account and a testnet Bitcoin wallet.

More information about the test environment can be found [here.](https://btcpay.com/docs/testing)

= The btcpay plugin does not work =
If btcpay invoices are not created, please check the following:

* The minimum invoice amount is USD 5. Please make sure you are trying to create a btcpay invoice for USD 5 or more (or your currency equivalent).
* Please make sure your btcpay merchant account is enabled for your transaction amounts. In your [btcpay merchant account](https://btcpay.com/dashboard/login/), go to Settings -> General -> Increase Processing Volume

= I need support from btcpay =
When contacting btcpay support, please describe your issue and attach screenshots and the btcpay logs.

btcpay logs can be retrieved in your Wordpress / Woocommerce environment:

* Enable logging in your btcpay plugin: Plugins -> Settings -> Debug Log -> Enable logging
* Download the logs from Plugins -> Logs

You can email your issue report to support@btcpay.com






== Upgrade Notice ==








== Changelog ==


= 2.2.24 =
* Bug: In some circumstances the auto update might crash the wordpress dashboard

= 2.2.23 =
* Setting Keep store level settings to transaction speed would still override store's setting
* Add low-medium transaction speed
= 2.2.22 =
* Fix crash on some stores Cannot use object of type stdClass as array in... on the dashboard

= 2.2.21 =
* Add event_invoice_expiredPaidPartial handling

= 2.2.20 =
* Do not crash plugin page if update detection fails, be more resilient

= 2.2.19 =
* Can detect new update in plugin page

= 2.2.18 =
* Ignore IPN if another payment method for the order has been chosen (#2)
* Can detect new update in plugin page

= 2.2.17 =
* Fix a race condition if process_payment called twice
* Can decide to ignore a BTCPay event

= 2.2.16 =
* Handle 'expired' IPN
* Handle 'invoice_paidAfterExpiration' IPN event

= 2.2.15 =
* Wrong function call resulting in undefined wc_reduce_stock_levels() (#84)
* Syntax error in class-wc-gateway-bitpay.php (#80)
* Make sure that if redirect url is redefined, it has order information Added
* Redirect page displays 'payment successful' even for unpaid invoices (#81)

= 2.2.14 =
* (fixed via PHP package update) Price must be formatted as a float (#78)
* Fixed WC 2.5 compatibility, with get_billing_email() error (#83)

= 2.2.13 =
* Fixed wrong function call resulting in undefined wc_reduce_stock_levels() (#84)
* Fixed syntax error in class-wc-gateway-bitpay.php (#80)
* Fixed price must be formatted as a float (#78)
* Added redirect page, displaying 'payment successful' even for unpaid invoices (#81)

= Step-by-step guide with screenshots =

Having trouble setting it up? Check out the visual guide for installing the Bitcoin Payment Extension on a clean version of WooCommerce on our blog:
[https://github.com/btcpayserver/woocommerce-plugin](https://github.com/btcpayserver/woocommerce-plugin)

[Plugin not working? Most common plugin issues](https://github.com/btcpayserver/woocommerce-plugin)  ?? all links for plugs need to be download from Wordpress 

== Screenshots ==

1. BTCPay payment form - cryptocurrency selection window
2. Some of the 40+ cryptocurrencies supported by BTCPay
3. BTCPay Bitcoin Payment Page - Invoice
4. Merchant dashboard on BTCPay

**Comment by Kukks** [comment]
@NicolasDorier  Can you create a branch in here for the wp-plugin specific version?

**Comment by Kukks** [comment]
Do we want to update both github plugin and wordpress plugin repo version to replace all mentions of bitpay?  One big issue I see is if someone tries to replace an existing installation with the new version. There are major breaking changes to be made and will only be viable for fresh installations

Just from a quick glance in the plugin:
* Db tables named `woocommerce_bitpay` conflicts with original bitpay plugin for sure
* WooCommerce patment gateway id is set to`woocommerce_update_options_payment_gateways_bitpay`
* ..and so forth( i went through the code and there is an inevitable conflict between bitpay plugin and btcpay plugin, the only way forward if we want to allo both to coexist is if anyone that upgrades to this new version does a fresh install of the plugin

**Comment by NicolasDorier** [comment]
@Kukks no need of separate branch.

**Comment by NicolasDorier** [comment]
It might hurt to migrate but we can provide a step by step tutorial.
